---
# Configuration sample file for Jingo (YAML)
application:
  title: PetWiki
  logo: './pet2.png'
  favicon: ''
  repository: './'
  docSubdir: ''
  remote: 'origin'
  pushInterval: 30
  secret: change me
  git: git
  skipGitCheck: false
  loggingMode: 1
  pedanticMarkdown: true
  gfmBreaks: true
  staticWhitelist: '/\.png$/i, /\.jpg$/i, /\.gif$/i'
  proxyPath: ''
authentication:
  google:
    enabled: false
    clientId: replace me with the real value
    clientSecret: replace me with the real value
    redirectURL: ''
  github:
    enabled: false
    clientId: replace me with the real value
    clientSecret: replace me with the real value
    redirectURL: ''
  ldap:
    enabled: false
    url: 'ldap://example.org:389'
    bindDn: ''
    bindCredentials: ''
    searchBase: 'ou=people,dc=example,dc=org'
    searchFilter: '(uid={{username}})'
    searchAttributes: ''
  local:
    enabled: true
    accounts:
      - username: 'kaue'
        passwordHash: '3aac157f2f2b212c4595afc50ddee13e37957f21'
        email: 'kauelopesmoraes22@gmail.com'
features:
  markitup: false
  codemirror: true
  gravatar: true
server:
  hostname: 192.168.0.67
  port: 6067
  localOnly: false
  baseUrl: ''
  CORS:
    enabled: false
    allowedOrigin: '*'
authorization:
  anonRead: false
  validMatches: .+
  emptyEmailMatches: false
pages:
  index: PET-Wiki
  title:
    fromFilename: true
    fromContent: false
    asciiOnly: false
    lowercase: false
  itemsPerPage: 10
customizations:
  sidebar: _sidebar.md
  footer: _footer.md
  style: _style.css
  script: _script.js

